name: Native AOT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            runtime: osx-x64
          - os: windows-latest
            runtime: win-x64
          - os: ubuntu-latest
            runtime: linux-x64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x.x
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.runtime }}
        
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: publish-${{ matrix.runtime }}
          path: bin\Release\net8.0\${{ matrix.runtime }}\publish\